---
out_dir: results
metric_best: accuracy
wandb:
  use: false
  project: GPSE-arxiv
dataset:
  format: OGB
  name: ogbn-arxiv
  task: node
  task_type: classification
  transductive: true
  node_encoder: true
  node_encoder_name: GPSE
posenc_GPSE:
  enable: true
  rand_type: NormalSE
  model_dir: pretrained_models/gpse_molpcba.pt
  dim_pe: 32
  use_repr: true
  repr_type: no_post_mp
  model: mlp
  layers: 2
  virtual_node: true
  input_dropout_be: 0.5
  input_dropout_ae: 0.2
  raw_norm_type: none
  gnn_cfg:
    head: inductive_hybrid_multi
    layers_pre_mp: 1
    layers_mp: 20
    layers_post_mp: 2
    dim_inner: 512
    layer_type: resgatedgcnconv
    multi_head_dim_inner: 32  # use dim_inner if None
    stage_type: skipsum
    batchnorm: true
    act: relu
    dropout: 0.2
    agg: mean
    normalize_adj: false
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  att_heads: 1
  att_dropout: 0.05
  att_concat_proj: false
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 256
  layer_type: gatev2conv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.5
  agg: mean
  residual: True
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.01
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
