---
out_dir: results
metric_best: auc
wandb:
  use: false
  project: GPSE-proteins
dataset:
  format: OGB
  name: ogbn-proteins
  task: node
  task_type: classification_multilabel
  transductive: true
  node_encoder: true
  node_encoder_name: LapPE
  node_encoder_bn: false
  edge_encoder: false
  edge_dim: 8
  edge_encoder_bn: false
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
    stack_eigval: true
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  sampler: neighbor
  neighbor_sizes:
    - 32
    - 24
    - 16
    - 8
    - 4
    - 4
  batch_size: 2048
  eval_period: 10
  ckpt_period: 100
val:
  sampler: neighbor
  accelerator: cpu  # prevent GPU OOM during evaluation
model:
  type: gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  att_heads: 1
  att_concat_proj: false
  att_dropout: 0.1
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 256
  layer_type: gatev2conv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.0
  agg: mean
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.01
  max_epoch: 1000
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
