---
out_dir: results
metric_best: auc
wandb:
  use: false
  project: GPSE-proteins
dataset:
  format: OGB
  name: ogbn-proteins
  task: node
  task_type: classification_multilabel
  transductive: true
  node_encoder: true
  node_encoder_name: GPSE
  node_encoder_bn: false
  edge_encoder: false
  edge_dim: 8
  edge_encoder_bn: false
posenc_GPSE:
  enable: true
  rand_type: NormalSE
  model_dir: pretrained_models/gpse_molpcba.pt
  dim_pe: 32
  use_repr: true
  repr_type: no_post_mp
  model: Linear
  layers: 1
  virtual_node: true
  input_dropout_be: 0.4
  input_dropout_ae: 0.05
  raw_norm_type: none
  gnn_cfg:
    head: inductive_hybrid_multi
    layers_pre_mp: 1
    layers_mp: 20
    layers_post_mp: 2
    dim_inner: 512
    layer_type: resgatedgcnconv
    multi_head_dim_inner: 32  # use dim_inner if None
    stage_type: skipsum
    batchnorm: true
    act: relu
    dropout: 0.2
    agg: mean
    normalize_adj: false
  loader:
    type: neighbor
    batch_size: 512
train:
  mode: custom
  sampler: neighbor
  neighbor_sizes:
    - 32
    - 24
    - 16
    - 8
    - 4
    - 4
  batch_size: 2048
  eval_period: 10
  ckpt_period: 100
val:
  sampler: neighbor
  accelerator: cpu  # prevent GPU OOM during evaluation
model:
  type: gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  att_heads: 1
  att_concat_proj: false
  att_dropout: 0.1
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 256
  layer_type: gatev2conv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.0
  agg: mean
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.01
  max_epoch: 1000
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
