---
name_tag: GINE+LapPE
out_dir: results
metric_best: auc
wandb:
  use: false
  project: GPSE-MoleculeNet
dataset:
  format: OGB
  name: ogbg-moltox21
  task: graph
  task_type: multilabel
  transductive: false
  node_encoder: true
  node_encoder_name: Atom+LapPE
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: Bond
  edge_encoder_bn: false
  edge_dim: 300
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
    stack_eigval: true
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 300
  layer_type: gine2conv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.01
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.001
  max_epoch: 100
  optimizer: adamW
  weight_decay: 0.01
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
