---
out_dir: results
metric_best: auc
wandb:
  use: false
  project: GPSE-MolNetSmall
dataset:
  format: er
  task: graph
  task_type: classification
  transductive: false
  node_encoder: true
  node_encoder_name: ElstaticPE+LapPE+RWSE+HKdiagSE+EigVals
  node_encoder_bn: false
  split_mode: random
er:
  num_samples: 1000
  n_min: 100
  n_max: 100
  p: 0.1
posenc_ElstaticPE:
  enable: true
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: sym
    eigvec_norm: L2
    max_freqs: 4
    skip_zero_freq: true
    eigvec_abs: true
posenc_RWSE:
  enable: true
  kernel:
    times_func: range(2,22)  # if no self-loop, then RWSE1 will be all zeros
posenc_HKdiagSE:
  enable: true
  kernel:
    times_func: range(1,21)
randenc_NormalSE:
  enable: true
  dim_pe: 20
graphenc_CycleGE:
  enable: false
  kernel:
    times_func: range(2,9)
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 300
  layer_type: gine2conv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.003
  max_epoch: 100
  optimizer: adamW
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5