---
name_tag: GCN+rand
out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: false
  project: GPSE-PCQM4Mv2-subset
dataset:
  format: OGB
  name: PCQM4Mv2-subset
  task: graph
  task_type: regression
  transductive: false
  node_encoder: true
  node_encoder_name: Atom+NormalRE
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: Bond
  edge_encoder_bn: false
posenc_NormalRE:
  enable: true
  dim_pe: 128
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  layers_pre_mp: 1
  layers_mp: 16
  layers_post_mp: 1
  dim_inner: 172
  batchnorm: true
  layer_type: gcnconv
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
  stage_type: skipsum
optim:
  clip_grad_norm: true
  optimizer: adamW
  weight_decay: 1e-6
  base_lr: 0.0002
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
